#!/usr/bin/env bash
# transfers a file from our client to a server
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
file_path=$1
ip=$2
username=$3
pk_path=$4
op="-o StrictHostKeyChecking=no"
scp "$op" -i "$pk_path" "$file_path" "$username@$ip":~
