#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!\n" | sudo tee /var/www/html/index.html
sudo service nginx restart
