#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
      listen 80;
      root   /etc/nginx/html;
      index  index.html;
      location /redirect_me {
        return 301 www.linkedin.com/in/iheb-timoumi-576a311b0;
      }
}" > /etc/nginx/sites-available/default
sudo service nginx reload
