#!/usr/bin/env bash
# Installs nginx web server

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
    listen 80;
    root   /etc/nginx/html;
    index  index.html;
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
